FROM python:3.12-slim

# переменные окружения
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# зависимости
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# код приложения
COPY backend ./backend

# gunicorn + uvicorn воркер
CMD ["gunicorn", "backend.main:app", \
    "--worker-class", "uvicorn.workers.UvicornWorker", \
    "--bind", "0.0.0.0:8000", \
    "--workers", "2", \
    "--threads", "1", \
    "--timeout", "60"]
