services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    secrets:
      - db_user
      - db_pass
      - db_host
    environment:
      # если в коде сборка DSN из secrets, этого достаточно:
      DB_PORT: "5432"
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_pass
      DB_HOST_FILE: /run/secrets/db_host
    ports:
      - "80:8000"
    networks: [obnet]
    mem_limit: 512m
    cpus: 0.9

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks: [obnet]

networks:
  obnet:

secrets:
  db_user:
    file: ./run/secrets/db_user
  db_pass:
    file: ./run/secrets/db_pass
  db_host:
    file: ./run/secrets/db_host