services:
  optionboard-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: optionboard-backend
    depends_on:
      - db
    secrets:
      - db_user
      - db_pass
      - db_name
    ports:
      - "80:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:17
    restart: always
    secrets:
      - db_user
      - db_pass
      - db_name
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
      POSTGRES_DB_FILE: /run/secrets/db_name
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

secrets:
  db_user:
    file: ./run/secrets/db_user
  db_pass:
    file: ./run/secrets/db_pass
  db_name:
    file: ./run/secrets/db_name