services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    secrets:
      - db_user
      - db_pass
      - db_host
    environment:
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_pass
      DB_HOST_FILE: /run/secrets/db_host
    ports:
      - "8000:8000"
    networks: [obnet]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    # mem_limit: 512m
    # cpus: 0.9
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: /api
    ports:
      - "3000:80"
    networks: [obnet]
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  obnet:

secrets:
  db_user:
    file: ./run/secrets/db_user
  db_pass:
    file: ./run/secrets/db_pass
  db_host:
    file: ./run/secrets/db_host