services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    secrets:
      - db_user
      - db_pass
      - db_host
    environment:
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_pass
    ports:
      - "8000:8000"
    networks: [obnet]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: /api
    ports:
      - "3000:80"
    networks: [obnet]
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  obnet:
    driver: bridge